---
resources:
  - name: src
    type: git
    source:
      uri: https://github.com/csy08/councourse-simple.git
      branch: master
jobs:
  - name: hello-world
    plan:
      - get: src
        trigger: true
      - task: execute
        config:
          inputs:
            - name: src
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: python }
            tag: 3.6-alpine
          run:
            path: sh
            args: [ "PYTHONPATH=$PYTHONPATH:src/", "python", "src/scripts/main.py" ]
